/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooCFAuto000Func.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooCFAuto000Func) 

 RooCFAuto000Func::RooCFAuto000Func(const char *name, const char *title, 
                        RooAbsReal& _g1,
                        RooAbsReal& _g2) :
   RooAbsReal(name,title), 
   g1("g1","g1",this,_g1),
   g2("g2","g2",this,_g2)
 { 
 } 


 RooCFAuto000Func::RooCFAuto000Func(const RooCFAuto000Func& other, const char* name) :  
   RooAbsReal(other,name), 
   g1("g1",this,other.g1),
   g2("g2",this,other.g2)
 { 
 } 



 Double_t RooCFAuto000Func::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return sqrt(g1*g2) ; 
 } 



